### PR TITLE
Add Work/Education and Tagline info to Profile page

### PR DESCRIPTION
**Pull request by Xaconi**
Not sure if it's enough with this...

image

Need @Ananto30 to see if this is correct.

Solves #3

### CODE REVIEW

**Comment by Ananto30** [comment]
We don't store Address, Phone and we don't want to share Email. Please remove those and move the work under the name like in the place of "Web developer", and tagline under that. We don't need the word "Work/Education" and "Tagline" just the values will work.
Work and tagline should be in center and please follow the font format like the posts. Make it beautiful 😉 Thanks

**Comment by Ananto30** [comment]
@Xaconi Sorry, forgot to mention you 👆

**Comment by Xaconi** [comment]
This version suits better?

image

**Comment by Ananto30** [comment]
Looks nice! Thanks 🙏

**Pull request merged**
